disabled_rules:
  - nesting
  - large_tuple
  - identifier_name
  - sorted_imports
  - cyclomatic_complexity
  - line_length
  - function_body_length
  - file_length

opt_in_rules:
  - empty_count
  - explicit_init
  - redundant_nil_coalescing
  - attributes

included:
  - Sources
  - App
  - Tests

type_name:
  max_length: 50

type_body_length:
  warning: 280
  error: 400

reporter: xcode
