disabled_rules:
  - trailing_whitespace
  - nesting
  - large_tuple
  - identifier_name
  - sorted_imports
  - trailing_newline
  - statement_position
  - colon
  - cyclomatic_complexity
  - shorthand_operator
  - line_length
  - function_body_length
  - file_length
  - switch_case_alignment
  - attributes

opt_in_rules:
  - empty_count
  - explicit_init
  - redundant_nil_coalescing
  - attributes

included:
  - Sources
  - App
  - Tests

type_name:
  max_length: 50

reporter: xcode
