name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          xcodebuild -version

      - name: Build Xcode project
        run: |
          xcodebuild -project SwiftCheetahApp.xcodeproj \
            -scheme SwiftCheetahApp -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO build

      - name: Install SwiftLint
        run: |
          brew update
          brew install swiftlint || true

      - name: Run SwiftLint
        run: swiftlint lint --quiet || swiftlint lint --strict

      - name: SwiftPM tests (engine only)
        run: swift test --parallel

